### ISSUE TITLE
Validering av respons gjøres feil

### ISSUE THREAD

**Issue by asjafjell** [difi/oppslagstjeneste-klient-dotnet#20]
For å validere responsen, krever biblioteket nå at man sender inn sertifikatet vi skal validere mot. Biblioteket skal selv validere det mot sertifikatene gitt av [Difi]( http://begrep.difi.no/SikkerDigitalPost/utkast/sikkerhet/sertifikathandtering).

**Comment by asjafjell** [comment]
Denne kan ikke gjennomføres fordi sertifikatet kommer ikke med responsen i V4. Jeg må innrømme at jeg ikke husker helt hvorfor det var slik, @aberner. Vil dette bli en del av V5, som det er ønske om at vi skal integrere mot?

**Comment by aberner** [comment]
la dette inn i på milestone for versjon 5 der sertifikatet vil bli returnert av Difi i responsen slik som i digital post. 
jeg vil detaljere issuene knyttet til versjon 5 fremover.

**Comment by asjafjell** [comment]
Flott! Hvis du kan garantere at det kommer i versjon 5, så kan vi legge denne oppgaven på vent inntil videre. Det er gjort en del oppryddingsarbeid her som vi får ta tak i videre når integrasjon mot versjon 5 starter.

On 27 Nov 2015, at 14:17, Arne Berner <notifications@github.com<mailto:notifications@github.com>> wrote:


la dette inn i på milestone for versjon 5 der sertifikatet vil bli returnert av Difi i responsen slik som i digital post.
jeg vil detaljere issuene knyttet til versjon 5 fremover.

**Comment by asjafjell** [comment]
Denne er nesten ferdig i #29, og kan implementeres så snart sertifikatet er i responsen.

**Comment by asjafjell** [comment]
Dette er nå implementert i [v5.0.5907.27251-beta](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.0.5907.27251-beta).
