### ISSUE TITLE
ProxyPort leses ikke fra konfig

### ISSUE THREAD

**Issue by bjornjensen** [difi/oppslagstjeneste-klient-dotnet#21]
ProxyPort leses ikke fra konfigfila.
Ved å legge inn 
            ProxyPort = SetFromAppConfig<int>(Prefix + ":ProxyPort", 80);
i konstruktøren til Klientkonfigurasjon, fungerer det.

**Comment by asjafjell** [comment]
Beklager sent svar. Dette vil bli fikset mot versjon 5 av Oppslagstjenesten som vi jobber med nå.

**Comment by asjafjell** [comment]
Dette er nå implementert i [v5.0.5907.27251-beta](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.0.5907.27251-beta).
