### ISSUE TITLE
Kall til Oppslagstjeneste feiler ved CurrentUICulture = "nb-NO"

### ISSUE THREAD

**Issue by aklefdal** [difi/oppslagstjeneste-klient-dotnet#23]
Dersom kall til for eksempel HentPersoner gjøres når CurrentUICulture er satt til "nb-NO", så feiler det før selve kallet blir sendt avgårde til Difi:

	System.Xml.XmlException was unhandled by user code
	  HResult=-2146232000
	  LineNumber=0
	  LinePosition=0
	  Message=	Validation error: Attributtet PrefixList er ugyldig - Verdien  er ugyldig i henhold til datatypen http://www.w3.org/2001/XMLSchema:NMTOKENS - Attributtverdien kan ikke være tom.

	  Source=Difi.Oppslagstjeneste.Klient
	  StackTrace:
		   ved Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.SendEnvelope(AbstractEnvelope envelope)
		   ved Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.HentPersoner(String[] personidentifikator, Informasjonsbehov informasjonsbehov)
		   ved UDI.ULFESB.DigitalPost.Core.Difi.DifiOppslagstjeneste.GjorOppslag(String personidentifikator) i C:\s\V09\UIP\DigitalPost\Core\Difi\DifiOppslagstjeneste.cs:linje 32
		   ved UDI.ULFESB.DigitalPost.IntegrationTests.Forbindelse mot Difi.Vi har forbindelse med Difi oppslagstjeneste() i C:\s\V09\UIP\DigitalPost\IntegrationTests\ForbindelseMotDifi.fs:linje 24
	  InnerException: 

Dette er kun observert på Windows 7, og jeg har ikke klart å reprodusere feilen på Windows 8.1.

**Comment by asjafjell** [comment]
Vi skal prøve å reprodusere denne i løpet av kort tid.

**Comment by kristianenge** [comment]
Hvilken versjon av klientbiblioteket bruker du @aklefdal ? Skjer det hver gang du kjører integrasjonstestene?

Jeg har forsøkt å gjenskape problemet, men ingenting av det jeg har testet virker å ha noe å si.
Hittil har jeg testet å:
 - sette CurrentUICulture og CurrentCulture i kode 
  - Testet med "nb-NO", "en-US", "en-GB" og "fr-LU" 
 - endre alt av regionsettings i Windows til "nb-NO"  

Jeg sitter på Windows 10 Home 64bit (via VMware fusion).

**Comment by aklefdal** [comment]
Feilen ble kun observert i Windows **7**...

**Comment by aklefdal** [comment]
Jeg har fortsatt en maskin som kjører Windows 7 på prosjektet. Der skal jeg laste ned siste versjon av klientbiblioteket, og se om jeg få reprodusert feilen. (Det er noen måneder siden sist jeg jobbet med oppslagstjenesten...)

**Comment by kristianenge** [comment]
Takk @aklefdal. Jeg har ingen windows 7 maskin til rådighet, så setter pris på at du tester dette. 

Kunne du først ha kjørt en test med versjon [1.0.5637.22318](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/1.0.5637.22318). Skjer det for hvert request, eller er det sporadisk? 

Hvis du fortsatt opplever feil hadde det vært utrolig fint om du kunne oppdatere biblioteket til siste pre-release [5.0.5918.17482-beta](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.0.5918.17482-beta) og se om det har noe å si på resultatet.

Siden der er noen breaking changes til v5.0 vil jeg anbefale å hente ut eksempelkoden fra [dokumentasjonen](http://difi.github.io/oppslagstjeneste-klient-dotnet/v5.0/#eksempelforsending)

**Comment by asjafjell** [comment]
Vi har i praksis lagd en ny klient siden dette issuet ble oppdaget, så vi må nesten bare ta dette opp igjen om det skulle skje på nytt. Lukker denne.
