### ISSUE TITLE
Oppgradere klienten til å støtte v5 av grensesnittet

### ISSUE THREAD

**Issue by joergenb** [difi/oppslagstjeneste-klient-dotnet#25]
https://github.com/difi/begrep-Oppslagstjenesten vil bli oppdatert med dokumentasjon av endringer i grensesnittet.

**Comment by aberner** [comment]
Nå er det klart for å begynne på .NET-klienten.

Java-eksempelet og SoapUI-prosjektet på github (eigen branch) fungerer, så den kan brukes som et utgangspunkt:
https://github.com/difi/kontaktregisteret-klient/tree/VERSION_5 

Dokumentasjon av versjon 5 på begrepskatalogen, release 5.0.0.RC2:
http://begrep.difi.no/Oppslagstjenesten/5.0.0.RC2/ 
med tilhøyrande endringsliste:
https://github.com/difi/begrep-Oppslagstjenesten/compare/3.0.4...5.0.0.RC2

**Comment by asjafjell** [comment]
Den er god!

**Comment by aberner** [comment]
versjon 5 av oppslagstjenesten er oppgradert til SOAP 1.2
påse at korrekt content-type brukes på http requesten.
var tidligere: text/xml men må nå være: application/soap+xml

**Comment by kristianenge** [comment]
@aberner Content-type er nå endret til application/soap+xml. Sendt ny forespørsel til id-porten.

**Comment by aberner** [comment]
svar sendt fra idporten@difi.no

**Comment by asjafjell** [comment]
Lukker denne, da vi ikke trenger et eget _moderkort_ for versjon 5.

**Comment by aberner** [comment]
Det er viktig at også dokumentasjonen oppdateres.
Når jeg går hit:http://difi.github.io/oppslagstjeneste-klient-dotnet/ er det ikke dokumentasjonen knyttet til versjon 5 av biblioteket som vises. Så enten er den mangelfull, eller så er det et problem i forhold til versjonering av dokumentasjonen.

Mener at denne saken ikke kan lukkes før dokumentasjonen er på plass.

**Comment by asjafjell** [comment]
Dokumentasjon blir alltid oppdatert ved full release, ikke for hver beta release, da det gir mye ekstraarbeid. Denne issuen er, slik jeg ser det, ikke noe issue som beskriver noe som ikke er gjort eller fikset. _Kunde/Leverandør-forhold_ er en issue som fint står alene.

**Comment by aberner** [comment]
Ok. Bare dokumentasjonen så blir husket på kan denne lukkes.

**Comment by asjafjell** [comment]
Jobber med dokumentasjon nå, så lukker denne.
