### ISSUE TITLE
Legge inn støtte for kunde/leverandør forhold (onbehalfof)(V5)

### ISSUE THREAD

**Issue by joergenb** [difi/oppslagstjeneste-klient-dotnet#26]
Nytt, valgfritt felt i soap-header for organisasjonsnummer til Kunde.

**Comment by aberner** [comment]
ref. #25 så er det nå klart for å utvikle denne forbedringen.

**Comment by asjafjell** [comment]
Denne er implementert i [5.0.5917.27122](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.0.5917.27122-beta).
