### ISSUE TITLE
Legge inn støtte for å sende varslingsstatus i request (V5)

### ISSUE THREAD

**Issue by joergenb** [difi/oppslagstjeneste-klient-dotnet#27]
Nytt informasjonsbehov <varslingsstatus>.

**Comment by aberner** [comment]
ref. #25 så er det nå klart for å utvikle denne forbedringen.

**Comment by asjafjell** [comment]
Dette er nå implementert i [v5.0.5907.27251-beta](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.0.5907.27251-beta).
