### ISSUE TITLE
Legge inn støtte for å behandle varslingsstatus i respons (V5)

### ISSUE THREAD

**Issue by joergenb** [difi/oppslagstjeneste-klient-dotnet#28]
Dersom varslingsstatus = KAN_VARSLES -> kan følge samme logikk som i v4.
dersom varslingsstatus = UTGÅTT -> må vere mulig for dei som bruker biblioteket å ha eigen behandling av dette (i dette scenarioet vil dei ikkje motta <kontaktinfo>,<sertifikat>,..)

Oppgaven må detaljeres.

**Comment by aberner** [comment]
ref. #25 så er det nå klart for å utvikle denne forbedringen.

**Comment by asjafjell** [comment]
Kan dere legge inn mer informasjon om denne oppgaven?

**Comment by aberner** [comment]
I versjon 5 av oppslagstjenesten er det lagt inn støtte for at Avsendere kan sette informasjonsbehov = VarslingsStatus

ref:
- http://begrep.difi.no/Oppslagstjenesten/utkast/varslingsstatus
- http://begrep.difi.no/Oppslagstjenesten/utkast/HentPersonerForespoersel

Dersom Avsender bruker dette flagget så er det for å få avklart om kontaktinformasjonen kan brukes for varsling. Ved slike forespørsler vil responsen inneholdet et felt: <varslingsstatus> som enten har verdien: KAN_VARSLES eller KAN_IKKE_VARSLES

Når responsen er KAN_VARSLES så vil varslingsinfo og info om digital postkasse bli utlevert.

Når responsen er KAN_IKKE_VARSLES vil ikke <kontaktinformasjon> , <Sikkerdigitalpostadresse> eller <x509Certificate> utleveres. Dette er nødvendigvis ikke fordi disse feltene ikke eksisterer, men kan også ha sin årsak i at varslingsinformasjonen er eldre enn 18 måneder.

Så det viktigste her er at biblioteket åpner for å sende requester med informasjonsbehov=varslingsstatus og at biblioteket håndterer responsen korrekt.

**Comment by asjafjell** [comment]
Dette er nå implementert i [v5.0.5907.27251-beta](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.0.5907.27251-beta).
