### ISSUE TITLE
Klart ikke parse svar fra serveren

### ISSUE THREAD

**Issue by skathayat** [difi/oppslagstjeneste-klient-dotnet#30]
Plutselig fikk denne feilen i dag. Kan dere ta en titt? Det var kjører fint i lang tid.
Jeg har sjekket - både avsender og Validering sertifikater er gyldige.

Se snapshot.
![image](https://cloud.githubusercontent.com/assets/1191568/13051583/3ab10b4e-d3fa-11e5-9182-30b7605df2f7.png)

Gist Link
https://gist.github.com/skathayat/cbaf6c1c4f20650c2492

**Comment by kristianenge** [comment]
@aberner Dette er samme feil vi opplever. Kan dere sjekke at ver2 miljøet har det bra?

**Comment by aberner** [comment]
hei,

jeg har videresendt dette internt.
Mulig at ver2 miljøet er oppdatert i forbindelse med en ny versjon som er på vei ut, og at det derfor har dukket opp en feil.

@skathayat bes å gå over til å bruke ver1 miljøet.

mens @kristianenge må avvente svar fordi tjenesten du skal bruke ikke er i ver1 miljøet.

**Comment by aberner** [comment]
oppdatering:

"Vi har problem med oppslagstjenesten etter deploy i ver 2 i går.
Utvikling trur dei har funnet feilen. Om ikkje feilen blir retta i løpet av formiddagen, tar vi rollback"

**Comment by skathayat** [comment]
@aberner Hva er ver1 service URL ?

**Comment by aberner** [comment]
URL: https://kontaktinfo-ws-ver1.difi.no/kontaktinfo-external/ws-v4

**Comment by skathayat** [comment]
ver1 miljøet fungerer.

**Comment by oyri** [comment]
Feilen blei desverre introdusert i deploy av ny versjon i går ettermiddag. Koden er rulla tilbake ca kl 10 i dag, så no skal ver2 fungere som før.

**Comment by kristianenge** [comment]
ver2 (v4) fungerer igjen, v5 er ikke tilgjengelig

**Comment by oyri** [comment]
v5 skal vera tilgjengeleg, om ikkje fullstendig ferdig implementert. Det er nokre kjente feil. Eg får svar frå v5: https://kontaktinfo-ws-ver2.difi.no/kontaktinfo-external/ws-v5. Kva tjeneste testar du @kristianenge ?
