### ISSUE TITLE
System.NullReferenceException' i Difi.Oppslagstjeneste.Klient.dll 

### ISSUE THREAD

**Issue by asjafjell** [difi/oppslagstjeneste-klient-dotnet#33]
(Flyttet fra [SikkerDigitalPost.Issues](https://github.com/difi/sikker-digital-post-klient-dotnet/issues/153), da den er direkte knyttet til Oppslagstjenesten, postet av @johnviggo)

Jeg sliter med følgende feilmelding ved forsøk på å kjøre metoden "HentPersoner" i Oppslagstjenesten.

System.NullReferenceException was unhandled
HResult=-2147467261
Message=Object reference not set to an instance of an object.
Source=Difi.Oppslagstjeneste.Klient
StackTrace:
at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.SendEnvelope(AbstractEnvelope envelope)
at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.HentPersoner(String[] personidentifikator, Informasjonsbehov informasjonsbehov)
....
Har brukt http://difi.github.io/oppslagstjeneste-klient-dotnet/ som utgangspunkt for følgende kode: https://gist.github.com/johnviggo/51e6cb01e7d861dad478

Jeg har blitt litt kastet inn i dette men får samme feilmelding på eksisterende test-kode som er skrevet. Tenkte bare jeg skulle starte på nytt for å forstå litt mer hva som skjer, men blir altså stoppet på samme vis.

Jeg bruker versjon 1.0.5637.22318 av Oppslagstjeneste-klient

**Comment by asjafjell** [comment]
Hei, @johnviggo og takk for fyldig og god beskrivelse med Gist og versjonsnummer. Jeg skulle gjerne fått sett mer av StackTrace for å se hva som faktisk er null. Kunne du gitt meg det?

**Comment by johnviggo** [comment]
Får du mer ut av dette?

> System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Difi.Oppslagstjeneste.Klient
  StackTrace:
       at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.SendEnvelope(AbstractEnvelope envelope)
       at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.HentPersoner(String[] personidentifikator, Informasjonsbehov informasjonsbehov)
       at Hemit.BizTalk.DifiTest.Program.Main(String[] args) in c:\VSOTFS\BizTalk\Development\jogr\Hemit.BizTalk.DifiSikkerPost\Hemit.BizTalk.DifiSikkerPost\Program.cs:line 21
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by asjafjell** [comment]
Kunne du sjekket at sertifikatene faktisk blir initialisert riktig? Sjekk at de ikke blir `null`. Det blir det raskt mye krøll av.

**Comment by johnviggo** [comment]
Begge sertifikatene ser ok ut. Ikke noe null å se.

**signeringsSertifikat**:

{[Subject]
  SERIALNUMBER=883974832, CN=ST OLAVS HOSPITAL HF, O=ST OLAVS HOSPITAL HF, C=NO

[Issuer]
  CN=Buypass Class 3 CA 3, O=Buypass AS-983163327, C=NO

[Serial Number]
  7401EBD956ACEADAD060

[Not Before]
  16.04.2013 15:03:49

[Not After]
  28.05.2016 14:09:44

[Thumbprint]
  CE5E1B25BF811536B9833BA1EDD90F05519A4C72
}

**valideringsSertifikat**:

{[Subject]
  SERIALNUMBER=991825827, CN=DIREKTORATET FOR FORVALTNING OG IKT, OU=VER, O=DIREKTORATET FOR FORVALTNING OG IKT, C=NO

[Issuer]
  CN=Buypass Class 3 CA 3, O=Buypass AS-983163327, C=NO

[Serial Number]
  31B678C06885DC85143B

[Not Before]
  07.03.2013 15:00:38

[Not After]
  07.03.2016 15:00:35

[Thumbprint]
  A47D57EAF69B627710FA0D06EC77500BAF71C432
}

**Comment by asjafjell** [comment]
Om sertifikatene er riktig satt så ser jeg ingen grunn til at det skal feile. Om den personen du prøver å hente ut ikke eksisterer så skal du få et element tilbake som sier akkurat dette. Er det muligheter for at det er noe rettighetstrøbbel her, @aberner?

**Comment by joergenb** [comment]
Dersom organisasjonsnummeret ikkje har fått tilgang, så returnerer vi ein SOAP-feil som med beskrivelse av kva som gjekk gale (feks. "org.no har ikke fått tilgang", "utløpt sertifikat", "ikke gyldig virksomhetssertifikat", etc). Trur vi har rundt 10 eigne feilmeldingar.  Feilhåndteringa i biblioteket bør synleggjere denne feilmeldinga, slik at det blir lettare å feilsøke.

**Comment by johnviggo** [comment]
Jeg ser det er like før DIFI-sertifikatet jeg bruker går ut. Det er ikke allerede byttet antar jeg? Ikke noe der som kan sørge for denne feilen?

[Not After]
07.03.2016 15:00:35

Jeg får ingen SoapException. Har prøvd å catche både Difi.Oppslagstjeneste.Klient.Domene.Exceptions.SoapException og System.Web.Services.Protocols.SoapException.

**Comment by asjafjell** [comment]
Her er nok feilhåndteringen litt tynn, så det kan godt hende at det er derfor du ikke får ut feilmeldingen. Vi jobber med Oppslagstjenesten V5, og første beta kommer om ikke så lenge. Kan du gi et tidspunkt på når du sist sendte, og med hvilket orgnr?

**Comment by johnviggo** [comment]
Jeg har aldri fått det til å fungere, men jeg skal se om jeg kan finne noe info om når det ble testet ok sist.

Mht. "med hvilket orgnr". Antar du da mener orgnummer ut ifra sertifikatet? Jeg spesifiserer ikke no orgnummer når jeg tester nå. Det skal være samme sertifikat, men jeg skal som sagt sjekke litt.

**Comment by asjafjell** [comment]
Hvis vi har orgnr så kan jeg få Difi til å sjekke direkte i loggene for å se hva som feiler, som en midlertidig løsning. Jeg tenker på orgnummeret for sertifikatet ja.

**Comment by aberner** [comment]
Ja, fint om vi kan få en verifikasjon av org.nummeret i sertifikatet og samtidig om vi kan få verifisert URL'n/dns dere bruker til testmiljøet.

**Comment by johnviggo** [comment]
Jeg går mot https://kontaktinfo-ws-ver2.difi.no/kontaktinfo-external/ws-v4

Orgnummeret er 883974832.

**Comment by aberner** [comment]
Tilgangen i ver2 miljøet er sjekket for org.nummer 883974832
Tilgangen er gitt til tjenesten: hentPersoner

Så dette er ikke et tilgangsproblem.

**Comment by aberner** [comment]
@johnviggo  
Sertifikatet som brukes i testmiljøet går ut 07.03.2015 som du skriver.
Det er sendt ut e-post til alle kontaktpunkter om at dette byttes på man dag 07. mars kl.12.00
Det nye sertifikatet som vil bli brukt er lagt ut her: https://samarbeid.difi.no/kontakt-og-reservasjonsregisteret/dokumentasjon

Dersom du ikke er satt opp som kontaktpunkt for tjenesten så ta kontakt med idporten@difi.no så kan du bli satt opp og få varsel ved slike endringer i tjenesten seinere.

**Comment by johnviggo** [comment]
https://kontaktinfo-ws-ver2.difi.no/kontaktinfo-external/ws-v4 er testmiljøet antar jeg?

SErtifikatet jeg bruker for Stolav er produksjonssertifikatet. Er det dette dere forventer eller skal jeg bruke testesertifikatet?

**Comment by aberner** [comment]
Dere kan bruke det testmiljøet, men det korrekte testmiljøet for enklere testing er: https://kontaktinfo-ws-ver1.difi.no/kontaktinfo-external/ws-v4 
Altså vårt ver1 miljø.
Dere har tilgang til det miljøet også og det er de samme sertifikatene som brukes der.

Det sertifikatet vi bruker i test er ikke det samme som i produksjon, men det er utstedt fra Buypass sin produksjons-CA og ikke fra deres test-CA.
Du skal se det på OU feltet i vårt sertifikat at det er utstedt til test/verifikasjon

**Comment by johnviggo** [comment]
Jeg bruker dette: idporten-ver2.difi.no-v2.crt

{[Subject]
SERIALNUMBER=991825827, CN=DIREKTORATET FOR FORVALTNING OG IKT, OU=VER, O=DIREKTORATET FOR FORVALTNING OG IKT, C=NO

[Issuer]
CN=Buypass Class 3 CA 3, O=Buypass AS-983163327, C=NO

[Serial Number]
31B678C06885DC85143B

[Not Before]
07.03.2013 15:00:38

[Not After]
07.03.2016 15:00:35

[Thumbprint]
A47D57EAF69B627710FA0D06EC77500BAF71C432
}

**Comment by aberner** [comment]
korrekt sertifikat for testmiljøet (frem til mandag kl.12 som sagt)

**Comment by johnviggo** [comment]
Det er jo ikke mange kodelinjene jeg har skrevet, så vet ikke hva galt jeg kan ha gjort.

https://gist.github.com/johnviggo/51e6cb01e7d861dad478

Litt usikker på hvordan jeg skal kunne komme meg videre.

**Comment by asjafjell** [comment]
Det er blitt gjort noen endringer på Xml for feilmeldingen som kommer i responsen. Dette gjør at du ikke får den ut. En fiks er under utbedring nå, men gjøres mot V5-beta av Oppslagstjenesten. Hvis dere har tilgang mot V5, så kan du få teste den. Kommer med oppdatering her så snart den er klar.

**Comment by aberner** [comment]
Tilgangen til v4 og v5 er styrt av det samme. så de skal være på plass.
Overgangen fra v4 til v5 blir da bare å oppdatere klientbiblioteket og bruk ny url til v5 av tjenesten.

**Comment by johnviggo** [comment]
Det høres bra ut. Da prøver jeg igjen når den er klar.

**Comment by asjafjell** [comment]
Url til FunksjoneltTestmiljø og Produksjon er innebygd i klienten, så her skal det ikke være mulig å gjøre feil mer.

**Comment by aberner** [comment]
@asjafjell  merk at oppslagstjenesten har to funksjonelle testmiljø så begge miljø må være mulig å velge, men at det er Verifikasjon1 som er default funksjonelt testmiljø.

**Comment by asjafjell** [comment]
Bedre feilmeldinger skal være tilgjengelig i [v5.0.5907.27251-beta](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.0.5907.27251-beta). Dokumentasjon er ikke tilgjengelig, men det skal være lett å se endringene på det lille eksemplet ditt, @johnviggo.

**Comment by asjafjell** [comment]
Lukker denne. Lag ny sak for eventuelle nye hindringer, @johnviggo.
