### ISSUE TITLE
Uklar feilmelding ved XSD-validering

### ISSUE THREAD

**Issue by asjafjell** [difi/oppslagstjeneste-klient-dotnet#37]
Hvis backend har fått en ny Xsd-regel som ikke fanges opp i Oppslagstjenesteklienten, f.eks hvis backend er ny og klienten er gammel, så får man tilbake en feilmelding som sier svært lite - `Validation error`. Her burde man returnere valideringsresultatet fra backend og at det faktisk er validering av Xml som feiler.

**Comment by aberner** [comment]
@joergenb eller @aamundbr kan en av dere se på denne?

**Comment by aamundbr** [comment]
@aberner, @joergenb:Er enig i at dette er lite informative feilmeldinger. Dessverre er det såvidt meg bekjent webservice rammeverket som gjer denne valideringa og returnerer denne feilmeldinga (Spring WS basert stack). Vil tru av vi kan konfigurere dette bedre eller lage vår eigen implementasjon av dette, men det må i såfall definerast ei oppgåve i backlog på dette og prioriteres på vanlig måte.

Vil imidlertid påpeike følgande:

1. Slik vår praksis er vil vi aldri bryte kontrakten for ein eksisterende versjon av tjenesta. Endring av XSD vil alltid medføre ny versjon av tjenesta og nytt endepunkt.
2. Ved integrasjon mot ein ny versjon bør ein ta ugangspunkt i denne tjenesta sin WSDL/XSD og generere klientstubber ut frå denne. Det er som regel ein dårlig ide å skrive xml for hånd. Dette bør redusere problema med syntaktisk ugyldige meldingar.

Men misforstå meg riktig, eg meiner at vi bør gjere noko her, men det er opp til p.o. å prioritere.

**Comment by asjafjell** [comment]
Dette gjelder også om vi slår av Xsd-validering i klientbiblioteket. Det vil da være likt med slik det vil kunne bli for andre som integrerer mot endepunktet uten klientbiblioteket. Det er alfa omega for å komme seg videre med informative feilmeldinger her.

**Comment by asjafjell** [comment]
Når det er sagt, så har vi prøvd alle mulige omveier for å klare å gå gjennom WSDLen som dere tilbyr, men det må nok gjøres noen endringer backend for at vi i .NET skal kunne bruke den for å integrere. Dette får vi se på når det nærmer seg neste versjon, om det lar seg gjøre.

**Comment by asjafjell** [comment]
Jeg foreslår at dette kortet lukkes inntil videre siden det ikke er et klientbibliotek-problem. Hva tenker du, @aberner?

**Comment by joergenb** [comment]
Eg er einig i at dette først må håndterast sentralt.  Eg har oppretta PBLEID-10903 som Difi-intern referanse.  Ved neste versjon, bør det jobbes mer med bla. WS-security slik løsningen fungrer mer sømløst med .NET-rammeverk.
