### ISSUE TITLE
Validerings sertifikat for test (Test_Difi.cer) er utgått

### ISSUE THREAD

**Issue by SteinarS** [difi/oppslagstjeneste-klient-dotnet#38]
For versjon 1 av klienten, kreves det at man har et validerings sertifikat.
Sertifikatet for test miljøet er utgått og kan ikke benyttes.
Dette sertifikatet er beskrevet her: http://difi.github.io/oppslagstjeneste-klient-dotnet/

Har dere et nyere sertifikat som kan benyttes mot test med versjon 1 klient?

**Comment by aberner** [comment]
Det nye sertifikatet er lagt ut på http://samarbeid.difi.no
Ta eventuelt kontakt med idporten@difi.no

**Comment by asjafjell** [comment]
Ser ut som denne løste seg, så jeg lukker den bare.
