### ISSUE TITLE
Ingen innstilling for ver1 test-miljø?

### ISSUE THREAD

**Issue by geirsagberg** [difi/oppslagstjeneste-klient-dotnet#54]
Ut i fra https://github.com/difi/oppslagstjeneste-klient-dotnet/blob/master/Difi.Oppslagstjeneste.Klient/Milj%C3%B8.cs ser det ut til at man kan sette enten prod-miljø eller ver2-miljø. 

Slik jeg har forstått det, kan ver2 være nyere enn prod-versjonen, mens ver1 skal være lik prod. Burde det ikke da også være mulig å velge ver1?

Jeg har spesifikt merket problemer i test-miljøet vårt hos Enova når vi bruker ver2, mens den samme koden fungerer helt fint mot prod.

**Comment by aberner** [comment]
ja, det er riktig. Det er VER1 som skal være PRIMÆRT funksjonelt testmiljø.
Ver2 skal også være tilgjengelig som et mulig valg, men det er kun ved spesielle behov.

Denne feilrettingen må prioriteres.

**Comment by asjafjell** [comment]
Dette skal prioriteres. I mellomtiden går det an å endre url for test til å gå mot ver1 på funksjonelt testmiljø.




On Thu, Apr 14, 2016 at 1:13 AM -0700, "Arne Berner" <notifications@github.com<mailto:notifications@github.com>> wrote:


ja, det er riktig. Det er VER1 som skal være PRIMÆRT funksjonelt testmiljø.
Ver2 skal også være tilgjengelig som et mulig valg, men det er kun ved spesielle behov.

Denne feilrettingen må prioriteres.

-

**Comment by kristianenge** [comment]
Dette er løses i versjon [5.1.5952.22633](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.1.5952.22633)
