### ISSUE TITLE
Valideringsfeil - Attributtet PrefixList er ugyldig

### ISSUE THREAD

**Issue by andre-waage-sorensen** [difi/oppslagstjeneste-klient-dotnet#65]
Når vi forsøker å gjøre et `HentPersoner` kall med `Informasjonsbehov.Kontaktinfo` flagget satt, så får vi alltid følgende feil:

`Attributtet PrefixList er ugyldig - Verdien  er ugyldig i henhold til datatypen http://www.w3.org/2001/XMLSchema:NMTOKENS - Attributtverdien kan ikke være tom.`

Kall-stacken begynner med:

_Difi.Oppslagstjeneste.Klient.OppslagstjenesteHelper.ValidateRequest(AbstractEnvelope envelope)_

Vi har testet med flere versjoner inkludert den nyeste (5.3.5990.19571) og forsøkt mot alle de tre miljøene, men den samme feilen oppstår alltid.

I versjon 4 av klienten hadde vi et lignende problem som aldri ble løst, men da var det mulig å slå av valideringen av xml-en slik at kallet kunne fullføre. Det ser ikke ut til å lenger være tilfellet.

Hvis det er relevant så er tjenesten vår bygget i Visual Studio Pro 2013 Update 5 og benytter .NET 4.5.

**Comment by asjafjell** [comment]
Hei! Dette skal vi selvfølgelig ta tak i så raskt som mulig. Er dette noe som har skjedd hele tiden med versjon 5 av Oppslagstjenesten eller har det kommet nylig?

**Comment by asjafjell** [comment]
Vi har nå undersøkt og dette er et resultat av at Xsd-validatoren bare validerer feilmeldinger på engelsk. En hurtigfiks for deg er å endre språk på maskinen som kjører klienten til _EN-US_ så skal det fungere. Kom gjerne med tilbakemelding på om det fikser problemet ditt.

**Comment by andre-waage-sorensen** [comment]
Jeg har nå testet hurtigfiksen på en utviklermaskin og det ser ut til å løse problemet. Jeg mener at serveren som dette skal kjøre på allerede er engelskspråklig, så det er mulig det vil fungere der uten endringer. Vi får komme tilbake til dette når vi har fått mulighet til å teste det.

**Comment by asjafjell** [comment]
Vi kommer til å fikse slik at dette ikke blir avhengig av språk, men foreløpig er det eneste måten å unngå dette på.

**Comment by kristianenge** [comment]
Denne bug-en skal være løst i #66
