### ISSUE TITLE
Åpne for å kunne laste sertifikat fra StoreLocation.LocalMachine

### ISSUE THREAD

**Issue by fmsfeno** [difi/oppslagstjeneste-klient-dotnet#67]
I følge guide for .NET-klient for integrasjons med Difi’s Oppslagstjeneste skal avsendersertifikat installeres på Current User. Ser og at Api-Client-Shared har koden `X509Store x509Store = new X509Store(StoreName.My, StoreLocation.CurrentUser);` for å finne sertifikatet. Er det med hensikt at det er valgt Current User, eller er det en glipp?

Drift her har problem med å installere sertifikat på appol-brukeren. Når de følger guide på http://difi.github.io/oppslagstjeneste-klient-dotnet/v5.3/, blir sertifikat installert på administrator.

De mener det ville være mer naturlig å installere på maskinkonto. Ved å installere sertifikat i current user fungerer det dersom website kjører som vanlig bruker (for eksempel admin), men de ser ikke det som god praksis.

Blir sertifikat installert på maskinkonto kan følgende brukes i programkoden (hvertfall som fallback dersom sertifikat ikke blir funnet på Current User: `X509Store x509Store = new X509Store(StoreName.My, StoreLocation.LocalMachine); ` Prøvde å lage lokal kopi av _api-client-shared_, men dessverre for min test (men korrekt) kreves det rett PublicKeyToken på dll, slik at min test ikke virket.

Har dere veiledning for å installere sertifikat på appol bruker, eller er det mulig å få oppdatering på _api-client-shared_ så den kan bruke sertifikat på maskinkonto?

**Comment by asjafjell** [comment]
Hovedgrunnen til at vi har valgt å bruke `StoreLocation.CurrentUser` og `StoreName.My` er for å lett komme i gang å lage testintegrasjon fordi vi så mange slet med å legge inn sertifikater under testing.
Nå har problemet i større grad snudd til å være at mange integrerer slik som eksemplene viser, og hvis det ikke passer med det rigget som en avsender har så blir det usikkerhet på hvordan integrasjonen skal gjøres. 

Det kan hende at vi enten må se på en løsning som nærmer seg det du skisserer, eller gå over til å bedre vise i dokumentasjonen at du kan laste inn sertifikater selv vha konstruktøren som tar inn sertifikatet direkte, ettersom mange ikke ser at dette er mulig. 

Så løsningen din i første omgang er å laste inn sertifikat slik som du ser det blir gjort i _api-client-shared_ og bruke [denne konstruktøren](https://github.com/difi/oppslagstjeneste-klient-dotnet/blob/master/Difi.Oppslagstjeneste.Klient/OppslagstjenesteKonfigurasjon.cs#L21).

**Comment by asjafjell** [comment]
Denne skal nå være ute i en tidlig testversjon. Har dere mulighet til å teste [5.4.0.22873-alpha](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.4.0.22873-alpha) og komme med tilbakemelding på om det fungerer som ønsket,  @fmsfeno?

**Comment by asjafjell** [comment]
Har testet denne og det fungerer fint så langt jeg kan se. Om du har noen annen konfigurasjon enn `Personal` for `LocalMachine` så får du rope ut. Lukker denne.
