### ISSUE TITLE
Method not found: Difi.Felles.Utility.XmlValidator.get_ValidationWarnings()

### ISSUE THREAD

**Issue by fmsfjho** [difi/oppslagstjeneste-klient-dotnet#69]
Får feil når prøver gjøre oppslag: (SenderCertificate finner sertifikat på maskinkonto)
Progamkode:

    X509Certificate2 avsenderCert = SenderCertificate(avsendersertifikatThumbprint, Language.English);
    var konfigurasjon = new OppslagstjenesteKonfigurasjon(Miljø.FunksjoneltTestmiljøVerifikasjon1, avsenderCert);
    var register = new OppslagstjenesteKlient(konfigurasjon);
    var personidentifikator = new[] { user.PersonNumber };
    var personer = register.HentPersoner(personidentifikator,
                    Informasjonsbehov.Person,
                    Informasjonsbehov.Kontaktinfo,
                    Informasjonsbehov.VarslingsStatus);

Feilmelding ved kall `register.HentPersoner()`

```
System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'System.String Difi.Felles.Utility.XmlValidator.get_ValidationWarnings()'.
   at Difi.Oppslagstjeneste.Klient.OppslagstjenesteHelper.ValidateRequest(AbstractEnvelope envelope)
   at Difi.Oppslagstjeneste.Klient.OppslagstjenesteHelper.<SendAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.<HentPersonerAsynkront>d__11.MoveNext()
```

difi-oppslagstjeneste-klient (5.3.5990.19571) med avhengige moduler
og prøvd å oppdatere til difi-felles-utility-dotnet (0.6.6003.17696) og api-client-shared (1.0.5968.19413)

Testserver: win 2012 R2

**Comment by asjafjell** [comment]
Dette høres merkverdig ut. Vi skal ta en kikk på det så raskt som mulig!

**Comment by asjafjell** [comment]
Problemet er er at du oppdaterer difi-felles-utility-dotnet til versjon 0.6, som har endringer som ikke er kompatible med versjon 0.5. Om du nedgraderer den til 0.5.5970.18522 så skal alt fungere.

**Comment by kristianenge** [comment]
Denne er implisitt løst i #66 (hvis du oppdaterer oppslagstjeneste-klienten)
