### ISSUE TITLE
Kall til OppslagstjenesteKlient.HentPersoner henger / gir ikke respons

### ISSUE THREAD

**Issue by andre-waage-sorensen** [difi/oppslagstjeneste-klient-dotnet#70]
Når vi kjører unit tester (mot både prod og testmiljøet) så fungerer HentPersoner akkurat som forventet. Derimot ser HentPersoner kallet ut til å alltid gå i heng (aldri returnere) når vi utfører det via web servicen vår. Dette gjelder både om vi kjører mot prod eller testmiljø, og både om vi debugger (vha. IIS Express) eller kjører releasebuild direkte i IIS.

Brukeren som web servicen kjører i kontekst av skal ha tilgang til sertifikatene, så det er lite sannsynlig at det er problemet. Det kan nesten virke som om noe går i deadlock internt i Oppslagstjenesten pga. at det er i en flertrådet web service og ikke i en unit test.

Vi har satt opp logging med Log4Net og slått på logging av forespørsler og respons. Ved kjøring av unit tester gir dette oss følgende output:

```
2016-06-24 13:47:54,827 [13] Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient..ctor(:0)ev - Miljø: Difi.Oppslagstjeneste.Klient.Miljø, ProxyHost: , ProxyScheme: https, ProxyPort: 0, TimeoutIMillisekunder: 30000, SendPåVegneAv: , LoggForespørselOgRespons: True
2016-06-24 13:47:54,853 [13] Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient+<HentPersonerAsynkront>d__11.MoveNext(:0)ev - HentPersonerAsynkront(personidentifikator:System.String[] , informasjonsbehov:Difi.Oppslagstjeneste.Klient.Domene.Entiteter.Enums.Informasjonsbehov[])
```

samt at forespørsel / respons dataene logges i en annen fil. Når kallet gjøres fra web servicen derimot så får vi bare en linje med output og ingen forespørsel / respons output:

`2016-06-24 13:51:10,948 [8] Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient..ctor(:0)ev - Miljø: Difi.Oppslagstjeneste.Klient.Miljø, ProxyHost: , ProxyScheme: https, ProxyPort: 0, TimeoutIMillisekunder: 30000, SendPåVegneAv: , LoggForespørselOgRespons: True
`

Uten noe mer output fra Oppslagstjenesten og uten mulighet til å steppe inn i koden, så blir det veldig vanskelig å debugge problemet videre.

For ordens skyld så benytter vi de nyeste versjonen av tjenesten:
- api-client-shared.1.0.5968.19413
- difi-felles-utility-dotnet.0.6.6008.19059
- difi-oppslagstjeneste-klient.5.3.6011.25286

Har dere noen innspill til hva vi kan gjøre videre?

**Comment by asjafjell** [comment]
Det er uhelidg at dere skal ha problemer med integrasjonen. Kan du gi oss kodesnutten du kjører som gir låsingen?

**Comment by andre-waage-sorensen** [comment]
Jeg vet ikke hvor mye hjelp det er i kodelinjen som henger uten å dele hele web servicen siden den samme koden fungerer når den blir kalt fra en unit test. Men kort fortalt skjer følgende:

```
// Konfig opprettes. Vi har prøvd alle de 3 miljøene og certThumb er en string med korrekt innhold.
OppslagstjenesteKonfigurasjon konfig = new OppslagstjenesteKonfigurasjon(Miljø.Produksjonsmiljø, certThumb);
// ...
konfig.LoggForespørselOgRespons = true;
// ...
OppslagstjenesteKlient register = new OppslagstjenesteKlient(konfig);
// fnr er en string[] med gyldige fødselsnr
return register.HentPersoner(fnr, Informasjonsbehov.Kontaktinfo).ToArray();  // <-- Dette kallet returnerer aldri (deadlock?)

```
Problemet er at kallet på siste linje aldri returnerer. Det går ikke an å pause debuggingen en gang, så det virker som om noe henger inne i OppslagstjenesteKlient.

**Comment by asjafjell** [comment]
Problemet her er sannsynligvis måten tråder håndteres i en webapp. `Oppslagstjeneste.HentPersoner` kaller overloaden `HentPersonerAsynkront().Result()`. Det som skjer da er at GUI-tråden venter på at  kallet skal fullføres, og kallet venter på at GUI-tråden skal bli ledig. Her må du nesten kalle `HentPersonerAsynkront()` directe og awaite det for at dette skal kjøre.

**Comment by andre-waage-sorensen** [comment]
Nå har jeg forsøkt å ta i bruk await og async uten å komme noe lenger. For meg ser det ut som om koden henger på akkurat det samme stedet som tidligere. Jeg skal innrømme at jeg aldri har brukt await eller async før, men jeg tror ikke det er i min kode problemet ligger.

Funksjonen som kalles ser nå slik ut:

```
public async Task<Person[]> HentPersoner(string[] fnr)
{
	OppslagstjenesteKlient register = new OppslagstjenesteKlient(konfig);
	IEnumerable<Person>    result   = await register.HentPersonerAsynkront(fnr, Informasjonsbehov.Kontaktinfo);
	
	return result.ToArray();
}

```
og kalles på følgende måte:

```
KontaktGateway gateway = new KontaktGateway();
var personer = gateway.HentPersoner(fnr);
Task.WaitAll(personer);

```

Jeg mistenker at dette er mer eller mindre det samme som HentPersoner gjør internt med HentPersonerAsynkront? Uansett så ser ikke dette ut til å hjelpe. Utifra dokumentasjonen jeg har funnet om await, så ser det uansett ut til å være mer relevant å bruke dette i en GUI-applikasjon enn i en ASMX / Web service handler.

En ting jeg oppdaget under debugging var at tre tråder var aktive i forskjellige metoder:

Tråd 1: **HentPersoner**
Tråd 2: **System.dll!System.Net.Dns.TryGetAddrInfo**
Tråd 3: **System.dll!System.Net.TimerThread.ThreadProc**

Kan det være at koden forventer et vindu som kan ta i mot 'messages' i en 'WindowProc' meldingspumpe? Jeg er litt usikker på hvordan en .NET web service håndterer f.eks. 'timer' meldinger.

Finnes det noe eksempel på bruk av OppslagstjenesteKlient i noe annet enn en GUI-applikasjon?

**Comment by kristianenge** [comment]
Hei @andre-waage-sorensen,
Grunnen til at det ikke fungerer for deg er nok fordi det ikke er Async hele veien, men vi har gjort en fiks i #68 som mest sannsynlig kommer til å løse problemet ditt også. Forsøk å installer siste beta versjon og se om det fungerer.

**Comment by andre-waage-sorensen** [comment]
Den nye beta versjonen ser ut til å fikse problemet. Takk for hjelpen!
