### ISSUE TITLE
Testmiljø bruker produksjonsertifikater mens klientbibliotek forventer testsertifikater

### ISSUE THREAD

**Issue by leifhv** [difi/oppslagstjeneste-klient-dotnet#71]
Prøver å bruke klientbiblioteket mot miljø FunksjoneltTestmiljøVerifikasjon1 men får da 'SecurityException: Sertifikatet i responsen er ikke gyldig' i OppslagstjenesteValidator.ValidateResponseCertificate.

Har testet å validere sertifikatet jeg får tilbake i min egen kode og validering feiler da riktig nok mot FunksjoneltTestmiljøSertifkater....men validering går bra mot Produksjonssertifikater.

Har fått beskjed om at det er produksjonssertifikater som brukes også i testmiljø, men klientbiblioteket ser ut til å forvente testsertifikater der:

```
namespace Difi.Oppslagstjeneste.Klient
{ 
     public class Miljø 
     { 
         internal Miljø(Uri url, CertificateChainValidator certificateChainValidator) 
...
         public static Miljø FunksjoneltTestmiljøVerifikasjon1 => new Miljø( 
             new Uri("https://kontaktinfo-ws-ver1.difi.no/kontaktinfo-external/ws-v5"), 
             new CertificateChainValidator(CertificateChainUtility.**FunksjoneltTestmiljøSertifikater**()) 
             ); 
```

Hvordan skal man få klientbibliotektet til å godta produksjonssertifikatene som returneres fra oppslagstjenesten når man kjører mot miljø FunksjoneltTestmiljøVerifikasjon1 ?

**Comment by aberner** [comment]
kan du oppgi noe mer av eksempel koden. 
* hvilken metode i oppslagstjenesten kaller du? 
* hvilket sertifikat i responsen er det du forsøker å validere? 

jeg skal se om noen andre kan bistå i å svare deg, men sikkert fint for dem å også få noe mer info fra deg om feilen du opplever.

Det er jo både SSL sertifikater, sertifikater i WS-Sec* og sertifikater levert inne i meldingen her, så det er veldig lett å blande litt sammen:
* SSL sertifikatet er et "prod" ssl-sertifikat
* WS-Sec sertifikatet som har signert SOAP meldingen er et "prod" virksomhetssertifikat
* mens sertifikatet returnert inn i meldingen som skal brukes for kryptering av post til digital post er et test-virksomhetssertifikat.

**Comment by asjafjell** [comment]
Du stiller de rette spørsmålene som vi ønsker å få svar på. Når det er sagt så kan det se ut som at problemet er at klienten ikke godtar sertifikatet som kommer i responsen, men avventer å sjekke dette til spørsmålene dine er besvart.

**Comment by leifhv** [comment]
Ja, for meg ser det ut til at klientbiblioteket ikke godtar sertifikatet i responsen.

- Her er kallet som feiler:

 var personer = _oppslagstjenesteKlient.HentPersoner(personidentifikator,
                Informasjonsbehov.Sertifikat,
                Informasjonsbehov.Kontaktinfo,                
                Informasjonsbehov.SikkerDigitalPost,
                Informasjonsbehov.VarslingsStatus);

- Her er exception jeg får:

2016-08-04 15:04:31,666 [1] Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.HentPersoner(:0)ev - System.AggregateException: One or more errors occurred. ---> Difi.Felles.Utility.Exceptions.SecurityException: Sertifikatet i responsen er ikke gyldig.
   at Difi.Oppslagstjeneste.Klient.Envelope.OppslagstjenesteValidator.ValidateResponseCertificate(SignedXmlWithAgnosticId signed)
   at Difi.Oppslagstjeneste.Klient.Envelope.OppslagstjenesteValidator.Validate()
   at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.ValidateResponse(AbstractEnvelope envelope, ResponseContainer responseContainer)
   at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.ValidateAndConvertToDtoObject[T](AbstractEnvelope requestEnvelope, ResponseContainer responseContainer)
   at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.<HentPersonerAsynkront>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.HentPersoner(String[] personidentifikator, Informasjonsbehov[] informasjonsbehov)

**Comment by asjafjell** [comment]
Nå har jeg testet å kjøre mot _FunksjoneltTestmiljøVerifikasjon1_ med et virksomhetssertifikat utstedt av _CN = Buypass Class 3 Test4 CA 3_, som er et testsertifikat, og det fungerer brillefint. Kunne du sjekket hvem som har utstedt sertifikatet (issuer), @leifhv?

**Comment by leifhv** [comment]
Da har jeg kjørt en ny test, for fortsatt 'SecurityException: Sertifikatet i responsen er ikke gyldig' i OppslagstjenesteValidator.ValidateResponseSertificate.

For å se på sertifikatet i responsen henter jeg ut 'BinarySecurityToken' fra response-xml og gjør den om til et X509Cerfificate2 (via ConvertFromBase64String).

Da får jeg et X509Certificate2 som har issuer:  

CN=Buypass Class 3 CA 3, O=Buypass AS-983163327, C=NO

Dette sertifikatet validerer som produksjonssertifikat, men ikke som testsertifikat. Veldig rart at vi får forskjellig sertifikat tilbake?

**Comment by aberner** [comment]
kan du også gi info om eventuelt fingerprint eller DN i sertifikatet du får utlevert ?

**Comment by leifhv** [comment]
Thumbprint:  4B60DA8781BBD99CDB7BDEAA57FD421E86D835B8

**Comment by asjafjell** [comment]
Jeg tror vi snakker litt rundt hverandre, @leifhv. Jeg snakker om mitt virksomhetssertifikat, ikke det i responsen. Når det er sagt, så har jo det fint lite å si når det er det i responsen som ikke er gyldig.

**Comment by asjafjell** [comment]
Jeg tror vi snakker litt rundt hverandre, @leifhv. Jeg snakker om mitt virksomhetssertifikat, ikke det i responsen. Når det er sagt, så har jo det fint lite å si når det er det i responsen som ikke er gyldig. Kan du lage en [gist](https://gist.github.com/) med koden du kjører og hvilken versjon av biblioteket du bruker?

**Comment by leifhv** [comment]
Ja, tror sertifkatet vårt er ok, esignatur kjører fint på samme maskin/prosess og da bruker vi samme virksomhetssertifikat.

Skal lage gist...

**Comment by leifhv** [comment]
Her ligger den aktuelle koden:  https://gist.github.com/leifhv/a30817e6193700a391a554f1894c4f44

Den kjører da mot versjon 5.3.6024.16371 av oppslagstjeneste dll'ene.

**Comment by asjafjell** [comment]
Nå har jeg gravd litt, og tror jeg vet hva det er som skjer her. Det som skjer er nok at du ikke har installert [rot- og mellomliggende sertifikater til Buypass og Commfides](http://begrep.difi.no/SikkerDigitalPost/sikkerhet/sertifikathandtering), noe som gjør at valideringen feiler. Jeg får samme sertifikat i responsen som du gjør (forståelig nok), men siden du antageligvis ikke har disse, så feiler det. Hvis min antagelse er korrekt så klarer ikke sertifikatvalidatoren å sette sammen kjeden. Dette er en bug som ligner på [#176 i Sikker Digital Post](https://github.com/difi/sikker-digital-post-klient-dotnet/issues/176).

**Comment by aberner** [comment]
Det er riktig at det sertifikatet du får tilbake i SOAP responsen (Thumbprint: 4B60DA8781BBD99CDB7BDEAA57FD421E86D835B8) er DIFI sitt sertifikat i ver1.

Det er riktig at det sertifikatet er et prod sertifikat utstedt fra (CN=Buypass Class 3 CA 3, O=Buypass AS-983163327, C=NO).

Litt forvirrende, men du bruker selv et test-virksomhetssertifikat for autentisering/signering og kryptering av responsen, mens responsen er signert av et prod-virksomhetssertifikat. Men det er slik oppsettet altså er.

**Comment by leifhv** [comment]
Hvis sertifikatet jeg får tilbake er et prod-sertifikat og klientbibliotektet forventer test-sertifikat kan jeg skjønne hvordan det skal kunne virke?  Fra https://github.com/difi/oppslagstjeneste-klient-dotnet/blob/master/Difi.Oppslagstjeneste.Klient/Milj%C3%B8.cs

public static Miljø FunksjoneltTestmiljøVerifikasjon1 => new Miljø(
            new Uri("https://kontaktinfo-ws-ver1.difi.no/kontaktinfo-external/ws-v5"),
            new CertificateChainValidator(CertificateChainUtility.FunksjoneltTestmiljøSertifikater())
            );

Hvis jeg endrer til å bruke new CertificateChainValidator(CertificateChainUtility.**ProduksjonsSertifikater**() fungerer valideringen av sertifikat i responsen som den skal, og det ville vel ikke skjedd hvis jeg manglet noen sertifikater på maskinen?

**Comment by asjafjell** [comment]
Kan du teste det og komme med tilbakemelding på om det fungerer? Det vil hjelpe oss med å forstå eventuelt hvorfor det blir slik.

**Comment by leifhv** [comment]
Her har jeg kjørt kun valideringen av responsesertifikatet:

![capture](https://cloud.githubusercontent.com/assets/20949429/17693946/c91c73c8-63a1-11e6-9487-9c1652696453.PNG)

Mulig det er noe tull med installasjon av sertifikatene hos oss, men da burde vel prod-validering også feilet?

**Comment by asjafjell** [comment]
Kan du teste å installere de mellomliggende sertifikatene og så prøve på nytt?

**Comment by leifhv** [comment]
Under Trusted Root Certification Authorities har jeg:
   -Buypass Class 3 Test4 Root CA
   -CPN Root SHA256 CA - TEST

Under Intermediate Certification Authorities/Certificates har jeg:
   -Buypass Class 3 TEST4 CA 3
   -Commfides CPN Enterprise-Norwegian SHA256 CA - TEST

Det siste skulle muligens vært 'Commfides CPN Enterprise-Norwegian SHA256 CA - TEST2'...ikke bare 'TEST' ? Prøver å legge inn det og så tester jeg på nytt.

**Comment by leifhv** [comment]
Da har jeg lagt til TEST2 sertifikatet også og kjørt ny test men får samme feil: 

'Difi.Felles.Utility.Exceptions.SecurityException: Sertifikatet i responsen er ikke gyldig'

Sertifikatene ser da sånn ut på maskinen...ser det riktig ut?

![capture](https://cloud.githubusercontent.com/assets/20949429/17730476/1fd45448-6469-11e6-8d5e-f98c2691169a.PNG)

![capture](https://cloud.githubusercontent.com/assets/20949429/17730587/97ddb5e2-6469-11e6-9caa-cae69e929f90.PNG)

**Comment by asjafjell** [comment]
Det er en bug at vi validerer med testsertifikatene her siden vi får et prodsertifikat fra Oppslagstjenesten , men sertifikatlageret på windows er litt spesielt, så selv om man ønsker å kun validere/bygge en kjede med et sett med sertifikater, så vil den prøve med de som er lokalt også om de finnes. Det er derfor det kan fungere, slik som i mitt tilfelle. Dette er også grunnnen til at jeg ville du skulle installere de mellomliggende sertifikatene.  Jeg beklager for at jeg var litt uklar, men det er altså produksjonssertifikatene på siden jeg linket til som jeg ønsker at du skal installere. 

Dette er altså en bug, men kan løses midlertidig med den løsningen jeg skisserte nå.

**Comment by leifhv** [comment]
Sorry, tok litt tid å få prodsertifikatene på plass, men det fungerte som det skulle når jeg fikk de på plass!

**Comment by asjafjell** [comment]
Flott! Takk for hjelpen med å lokalisere feilen.

**Comment by asjafjell** [comment]
Denne skal være fikset i [v5.4.0.23008](https://github.com/difi/oppslagstjeneste-klient-dotnet/releases/tag/v5.4.0.23008). Nå skal du kunne fjerne sertifikater som du har installert gjennom MMC. Test gjerne denne og kom med tilbakemelding.
