### ISSUE TITLE
Forbedring av feilmelding

### ISSUE THREAD

**Issue by kimbell** [difi/oppslagstjeneste-klient-dotnet#72]
Vi har kjørt mot Ver2 i lang tid uten problemer. Når jeg prøvde å bytte til Ver1, så fikke jeg feil. 

Vi har mye generisk logging på exceptions; Message property blir skrevet ut. I loggene så fant jeg følgende melding 'Sjekk klassemedlemmer for mer detaljer.' Som ikke sier meg spesielt mye. 

Når jeg fyrte opp debuggeren, så oppdaget jeg at denne exception typen hadde en property som heter Beskrivelse med følgende innhold 'Invalid service usage: Service owner 1111111111 does not have access to OPPSLAGSTJENESTEN'

Dette er en mye mere relevant feilmelding. Hvorfor vises ikke denne i Message property? Det er ikke et eneste rammeverk der ute som har et forhold til en property som heter Beskrivelse.

**Comment by asjafjell** [comment]
Takk for tilbakemelding!

Vi jobber kontinuerlig med å forbedre akkurat dette, og har nylig gått over til å bruke `Common.Logging` for å gjøre det mer fleksibelt for avsendere å bruke eget loggrammeverk. På selve loggmeldingene har vi også et forbedringpotensiale. Kan du utdype hva du mener med rammeverkene sitt forhold til properties?

**Comment by kimbell** [comment]
Poenget mitt er at dere legger en viktig feilmelding i en property som heter Beskrivelse i stedet for Message. Det som ligger i Message forteller meg ingenting om hva som feilet. De fleste loggerammeverk har ingen problemer med å skrive ut det som ligger I Message, en property som finnes på alle Exceptions. Beskrivelse er noe som bare finnes på Difi sine exceptions, og vil kreve tilpassninger for å få ut i loggene.

**Comment by asjafjell** [comment]
Du har et godt poeng her. Dette er noe vi bør få fikset og det bør ikke være mye arbeid å få dette til. Hvis du ønsker dette raskt i produksjon så mottas pull requests med glede!

**Comment by asjafjell** [comment]
Dette er fikset i [v6.0.1](https://github.com/difi/oppslagstjeneste-klient-dotnet/releases/tag/v6.0.1).
