### ISSUE TITLE
Rydde opp i avhengigheter mellom NuGet-pakker

### ISSUE THREAD

**Issue by aberner** [difi/oppslagstjeneste-klient-dotnet#77]
Avhengigheten mellom versjoner av de forskjellige Nuget pakkene deres begynner å bli et seriøst mareritt. 
Har akkurat oppdatert med siste versjon av oppslagstjenesten, og så lagt inn støtte for sikker post. 
 
  
Basert på dette ser ting greit, bortsett fra det finnes en nyere versjon av api-client-shared. Dette er et navn som ikke sier meg en dritt. Ingenting hinter til at den kommer fra Difi. 
 
Når jeg så fyrer opp web applikasjonen min, så får jeg denne fine meldingen.
 
Could not load file or assembly 'ApiClientShared, Version=1.0.5968.19413, Culture=neutral, PublicKeyToken=683b8efceae684a6' or one of its dependencies. The system cannot find the file specified. 
at Difi.Felles.Utility.Resources.Certificate.CertificateResource.GetCertificate(String[] path)
at Difi.Felles.Utility.Resources.Certificate.CertificateResource.Chain.GetDifiProductionChain()
at Difi.Oppslagstjeneste.Klient.Miljø.get_FunksjoneltTestmiljøVerifikasjon1()
 
Hvorfor den ikke automatisk går mot api-client-shared 1.1.0.24133 versjonen vi bruker aner jeg ikke. Vi begynner å få en del Windows servicer som også benytter Difi tjenestene, og det er ikke trivielt å sjekke at alle binding redirectene vi må legge inn faktisk stemmer på alle steder. 
 
Dere må begynne å tenke mer på hvordan dette skal brukes av andre. Akkurat nå er det å finne et sett med versjoner som fungerer sammen som å vinne i Lotto. Det er ikke bare å oppdatere med siste fra Nuget, vi må teste en del andre ting også. 
 
Hva er forskjellen på api-client-shared og difi-felles-utility-dotnet? Hvorfor ha to forskjellige fellesprosjekter? 
Digitial post er rimelig ubrukelig uten oppslagtjenesten siden man er avhengig av det som ligger der for å få sendt post. Hvorfor ikke bruke oppslagstjensten som basispakken, så tilby post som et supplement.

**Comment by asjafjell** [comment]
Slik jeg ser det så er spørsmålet ditt tredelt:

1. Det er vanskelig å bruke Sikker Digital Post og Oppslagstjenesten samtidig. Hvordan kan vi forbedre dette for brukerne?
2. Hvorfor har vi `api-client-shared` og `difi-felles-utility`?
3. Er det mulig å gjøre Sikker Digital Post og Oppslagstjenesten til én pakke som avsendere kan bruke?

Avhengigheter til andre Nuget-pakker og avhengighetskonflikter mellom Sikker Digital Post og Oppslagstjenesten har skapt mye hodebry for oss. Hovedgrunnen til dette var vi tidligere ikke hadde begrensninger på hvilke versjoner av `api-client-shared` og `difi-felles-utility` vi kunne avhenge av fra selve klientbilbiotekene.

Vi har nå angitt intervaller hvert klientbibliotek støtter for fellesbibliotekene. Hvis du ønsker å inspisere disse intervallene så kan du se det på Nuget.org, f. eks [her for SDP](https://www.nuget.org/packages/difi-sikker-digital-post-klient/1.10.0.25393), under Dependencies. I noen tilfeller kan man ende opp med at det ikke finnes releasede versjoner av SDP og OT med overlappende dependency. Sånn skal det ikke være, og vi prøver å unngå det.

For å gi oss selv litt mer spillerom så har vi i større grad _deprecate_-et metoder i bibliotekene slik at gamle versjoner skal kunne leve litt lenger, samtidig som vi strengt følger [SemVer](www.semver.org) for å bedre kunne resonnere rundt versjonsnumrene. Det kan være greit å vite at Visual Studio 2015 Update 1 har en bug som gjør at Nuget installerer versjoner av avhengigheter som vi ikke tillater. 

Hvis du sender over informasjon om hvilke versjon av OT og SDP du har problemer med, så kan vi sjekke hva som har skjedd her. 

2. `api-client-shared` er et hjelpebibliotek som Digipost utvikler og bruker i egne klientbiblioteker. Det inneholder en del funksjonalitet som ikke ligger i `difi-felles-utility`. Istedet for å duplisere denne funksjonaliteten mellom Difi- og Digipostklientbilbioteker har vi valgt å bruke dette som en komponent også fra SDP og OT.

3. Å slå sammen bibliotekene til ett bibliotek er et godt forslag, og er noe vi kan vurdere å gjøre. Det kommer med sine egne utfordringer, blant annet fordi OT vil dra med all SDP-funksjonaliteten uavhengig av om klienten egentlig ønsker å sende digital post. Dette bør utredes før vi gjør noe med det.

**Comment by kimbell** [comment]
At api-client-shared er et Digipost bibliotek, og ikke Difi er en interessant detalj. Jeg trodde greia var at vi kontaktet et endepunkt hos Difi, så var det server kode hos Difi som rutet requesten til Digipost eller Eboks. Det høres litt rart ut at man må benytte kode fra en av to mulige leverandørere når man skal gå igjennom et abstraksjonslag.

Jeg ser ikke for meg å slå sammen OT og SDP pakkene. Det gir mening at man ikke tar med SDP før man faktisk trenger det. Utfordringer har vært rundt de andre felles pakkene.

**Comment by asjafjell** [comment]
Jeg har nå testet å installere `Difi.Oppslagstjeneste.Klient 5.5.0.21929` og `Sikker.Digital.Post.Klient 1.10.1.28370`. Av en eller annen grunn så mangler en avhengighet til `System.Net.Http.Formatting.Extension`, noe som må fikses. Om denne pakken installeres så kjører disse helt fint i tospann. Hvis jeg sjekker _App.config_ etterpå så er følgende redirect automatisk lagt til:
```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="ApiClientShared" publicKeyToken="683b8efceae684a6" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.0.24133" newVersion="1.1.0.24133" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```
[Dokumentasjonen til Microsoft](https://msdn.microsoft.com/en-us/library/2fc472t2(v=vs.110).aspx) påpeker at dette er funksjonalitet som er lagt til i  .NET 4.5.1, men jeg observerer det også for .NET 4.5.0 som er det vi også har for klientbibliotekene. Mulig at dette er noe som skjer kun i Visual Studio 2015. Kan du gi mer info om utviklingsmiljøet ditt, @aberner?

**Comment by aberner** [comment]
@kimbell kan du svare på spm fra @asjafjell ?

**Comment by asjafjell** [comment]
Hvis du vil bruke en versjon uten den manglende avhengigheten til `System.Net.Http.Formatting.Extension` så kan du bruke en rykende fersk versjon [1.11.0](https://www.nuget.org/packages/difi-sikker-digital-post-klient/1.11.0).

**Comment by kimbell** [comment]
Vi har ikke oppgradert til 5.5 enda, vi kjører fortsatt på 5.3 som var nyeste versjon sist gang vi oppdaterte nuget pakkene våre.

**Comment by asjafjell** [comment]
Siden denne tråden ikke er et spesifikt issue og det har vært inaktivt i såpass lang tid så lukker jeg denne. Om det skulle være flere problemer så er det bare å opprette et nytt.

**Comment by codeape2** [comment]
Hei jeg bare lurer på som er anbefalt fiks dersom vi opplever dette problemet (altså Could not load file or assembly 'ApiClientShared, Version=1.0.5968.19413 osv.)

I miljøet der dette oppstår er det følgende versjoner av Difi-software:

* Difi.Oppslagstjeneste.Klient 5.5.0.21929 som refererer 
  * ApiClientShared 1.1.0.24133
  * Difi.Felles.Utility 0.8.0.27738 som refererer
    * Difi.Felles.Utility.Resources 0.8.0.27738 som refererer
      * ApiClientShared 1.0.5968.19413

Det er litt problematisk at referansehierarkiet har to versjoner av samme assembly.

Hva er anbefalt løsning?

**Comment by kimbell** [comment]
Den dll'en har alltid skapt problemer for Helsenorge. 9 av 10 ganger etter at man har oppdatert Nuget pakkene, så dukker denne opp. Eneste fiksen jeg har er å kjøre binding redirect. 

Relatert til helsenorge. 
For alle prosjekttyper som produserer en exe eller et web prosjekt, så ser det ut som binding redirect blir oppdatert i app.config eller web.config. Det virker som det er en bug i visual studio; dersom man oppdaterer nuget på sln nivå, så blir alle .config filene sjekket ut selv om de ikke har blitt endret. 

For prosjekter som bare produserer dll'er (SharePoint), så må redirect oppdateres via kode.

**Comment by codeape2** [comment]
Spm. til DIFI:

Om vi (dvs. Helsenorge.no) bytter til siste versjon av difi-oppslagstjeneste-klient (5.6.1) og difi-sikker-digital-post-klient (2.0.0), vil vi da sitte med samme problemet?

@kimbell Jeg gacet ApiClientShared 1.0.5968.19413 som en midlertidig quickfix på det ene INT-miljøet vårt, det løste tilsynelatende problemet, ser du noen grunn til å IKKE gjøre det på den måten?

**Comment by kimbell** [comment]
@codeape2 Det vil jo fungere, men spørsmålet er hvordan du får to forksjellige versjoner av dll'en deployet via SharePoint wsp systemet. Når du har oppdatert til nyeste versjon av nuget pakkene, så vil ikke det være spor av denne versjonen på filsystemet (nuget sletter de gamle versjonen). 

Helsenorge har støtt på problemet mange ganger, og binding redirect har løst problemet da. Man må bare sørge for at man får oppdatert alle steder. Med bevegelsen vekk fra SharePoint, så blir vel dette et mindre problem på sikt.
