### ISSUE TITLE
Oppdater til .NET Standard for å støtte .NET Core

### ISSUE THREAD

**Issue by severisv** [difi/oppslagstjeneste-klient-dotnet#85]
Hvis man benytter oppslagstjeneste-klienten fra et .NET Core-prosjekt får man advarselen `Package 'difi-oppslagstjeneste-klient 6.0.1' was restored using '.NETFramework,Version=v4.6.1' i
nstead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.`

Ved å legge til .NET Standard som _Target Framework_ i biblioteket vil man også støtte .NET Core-prosjekter.

Mer informasjon finnes her:  https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by aknutsen** [comment]
Heisann!

Jeg har sett litt på dette, og slik jeg forstår er dette litt problematisk ettersom oppslagstjenesten har en del dependencies i form av tredjepartsrammeverk som heller ikke er .NET Standard, men som i likhet med oppslagstjeneste-klienten er kompilert med .NET framework 4.5. Jeg prøvde å kjøre "Project Portability Analyzer" på prosjektet for å avgjøre om det er overkommelig å oppgradere til .NET Standard, men denne laget bare en tom rapport.

Det står forøvrig på planen for høsten å oppgradere biblioteket til .NET 4.6, men kanskje man skulle sett på om det er mulig å gjøre det kompatibelt med .NET Standard 2.0, som såvidt jeg skjønner gjør at det også vil fungere i en standard .NET Framework 4.6.2-applikasjon.

Innspill tas i mot med takk

**Comment by joergenb** [comment]
Hei.
Til orientering: Vi i Difi held på med å tilby oauth2-beskytta grensesnitt inn mot KRR. Eg veit ikkje om desse avhengigheitene/tredjepartsrammeverka dere diskuterer er relatert til SOAP, og at det sånn sett blir lettere å oppgradere dersom migrerer over til Oauth2.
https://difi.github.io/idporten-oidc-dokumentasjon/oidc_api_krr.html (work in progress)

**Comment by talisker77** [comment]
Er det aktuelt å tilpasse løsningen til .NETStandard/Core?

**Comment by guidemetothemoon** [comment]
Hei! Jeg lurer også på om det er planlagt å løfte oppslagstjeneste-klienten til .NET Standard/.NET Core? Per nå er det "en showstopper" for migrering av prosjektet vårt til .NET Core ..

**Comment by johnksv** [comment]
Pakken er nå oppdadert .net standard 2.0: https://github.com/difi/oppslagstjeneste-klient-dotnet/releases/tag/7.0.0
Lukker dermed denne.
