### ISSUE TITLE
difi-felles-utility-dotnet dependency conflict when updating to Difi.Felles.Utility 1.2.1 (from 1.2.0)

### ISSUE THREAD

**Issue by sukchr** [difi/oppslagstjeneste-klient-dotnet#86]
Error:
```
Unhandled Exception: System.IO.FileLoadException: 
Could not load file or assembly 'Difi.Felles.Utility, Version=1.2.0.0, Culture=neutral, PublicKeyToken=6e6972f540d5419a' or one of its dependencies. 
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Using code
```
var x = Difi.Oppslagstjeneste.Klient.Miljø.FunksjoneltTestmiljøVerifikasjon1;
```

With packages:
```
  <package id="difi-felles-utility-dotnet" version="1.2.1" targetFramework="net452" />
  <package id="difi-oppslagstjeneste-klient" version="6.0.1" targetFramework="net452" />
```

With app.config
```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Difi.Felles.Utility" publicKeyToken="6e6972f540d5419a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.1.0" newVersion="1.2.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

Created a small console-app here for reproducing the error: https://github.com/sukchr/difi-assembly-conflict

Following package-setup works fine:
```
  <package id="difi-felles-utility-dotnet" version="1.2.0" targetFramework="net452" />
  <package id="difi-oppslagstjeneste-klient" version="6.0.1" targetFramework="net452" />
```

**Comment by aslakjo** [comment]
Hi

We have reproduced the same issue with our example project. Thanks very much for the example. 

The combination that you are trying to do is not directly supported by us. We are currently testing out a new version of the felles-utility that upgrades to .net 4.6. And will be publishing it shortly. This version as this upgrade included. Does that solve it for you?

**Comment by sukchr** [comment]
Hi! Thanks for prompt reply! 

Could you please provide a date for publication of the fix?

**Comment by sukchr** [comment]
Hi, could you please give an estimated date for publication of fix?

**Comment by aslakjo** [comment]
Hi @sukchr 

Sorry for the wait, we encoundered some certificate problems with the smoke tests. 

However if you like to test out the new code you can do so today by building the 462 branch.

**Comment by sukchr** [comment]
Thank you. 

Could you please give an estimated date for publication of fix? This issue is a blocking issue for us.

**Comment by aslakjo** [comment]
I have now created a pull request agains your example repo. Please check if this is a solution for your. In addition to publish a version for the difi libraries i have updated the .net framework.

**Comment by sukchr** [comment]
Thank you for your feedback! 

However, we also need this to work with "difi-sikker-digital-post-klient" (of which we are currently using version 2.0.3).

Adding difi-sikker-digital-post-klient v2.0.3 to the equation yields:
```
Unable to find a version of 'api-client-shared' that is compatible with 'difi-sikker-digital-post-klient 2.0.3 constraint: api-client-shared (>= 2.0.0 && < 3.0.0)'.
```

**Comment by Lerberg** [comment]
"However if you like to test out the new code you can do so today by building the net46 branch."

How do I change to the net46 (or later) branch?

**Comment by johnksv** [comment]
Hi,
The following versions  of digdir/digipost libs should work together (code for .net core):
```
    <ItemGroup>
        <PackageReference Include="Difi.Felles.Utility" Version="5.0.1"/>
        <PackageReference Include="Difi.Felles.Utility.Resources" Version="5.0.1"/>

        <PackageReference Include="Difi.SikkerDigitalPost.Klient" Version="5.0.1"/>
        <PackageReference Include="Difi.SikkerDigitalPost.Klient.Domene" Version="5.0.1"/>

        <PackageReference Include="Digipost.Api.Client.Shared" Version="7.0.1"/>

        <PackageReference Include="Digipost.Signature.Api.Client.Core" Version="7.0.3"/>
        <PackageReference Include="Digipost.Signature.Api.Client.Portal" Version="7.0.3"/>
        <PackageReference Include="Digipost.Signature.Api.Client.Resources" Version="7.0.3"/>
        <PackageReference Include="Digipost.Signature.Api.Client.Scripts" Version="7.0.3"/>

        <PackageReference Include="difi-oppslagstjeneste-klient" Version="7.0.0"/>
        <PackageReference Include="Difi.Oppslagstjeneste.Klient.Domene" Version="7.0.0"/>
        <PackageReference Include="Difi.Oppslagstjeneste.Klient.Scripts" Version="7.0.0"/>
    </ItemGroup>
```
Closing. Please open a new issue if this still is a problem.

**Comment by sahilgarg-1359** [comment]
Hello. i am facing the below relatable issue.
Could not load file or assembly 'Difi.Felles.Utility, Version=2.0.1.52, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040). May you please help me asap.
