### ISSUE TITLE
Dependency til log4net i versjon 7.0.0

### ISSUE THREAD

**Issue by andreasle** [difi/oppslagstjeneste-klient-dotnet#96]
Hei,
Kunne dere fjernet dependency til log4net i versjon 7.0.0,  og heller hatt dependency til Common.Logging slik som i versjon 7.0.0.86-beta?

**Comment by johnksv** [comment]
Hei,
Enig i at avhengigheten til Common.Logging burde være videreført i stedet for å bli erstattet. Jeg er på det.

**Comment by johnksv** [comment]
Versjon 7.0.1 er nå ute med avhengighet til Common.Logging 3.4.1
Release: https://github.com/difi/oppslagstjeneste-klient-dotnet/releases/tag/7.0.1
NuGet: https://www.nuget.org/packages/difi-oppslagstjeneste-klient/7.0.1
